comp_dict = {'A':'T', 'T':'A', 'G':'C', 'C':'G'}

data = "AAGCGAGGTATTTTATCATCTCGCAGCTTCTACTACGTTGTGTTATGAAGCTCGACGAATGTGACCCGACCATAATCTACCGCTTAACTTGTTCTGGGGAAGCTTCCCCGTCGTTGATCGCGGTGCTGATCAGCTCATATAAAGCTTTGATATGCCATGCAGAGCAGTTCTTCCAATTAAATACTGGCCAGTTAATCCTTAACTAGTCACATGGGGCATACTGAGCAAACCAGATGGACTGTCCCCTTACGACAGAGCCGTTAAGGTTAATGGGGAGGCAAGACTATCTACCCGGAGACTGACAGGCTAGCAAGCTTTGCACCGGCCTTTTGAAAAGCAGCTAGCCCATGTAAGTGGCTACACATAGCATTAGGATCCTAGATGGTCCACAATGTCATACTGGGTTATGCAATTTCATTCAGTCAGATAGACCTAGATCTTCGCAGCTTGACGAGGAGTGCGCCCATAGCGCCTAGGGATAGGTATTGGGGTTGGGGGGATTGCGTCATGTCGGCCATCATGCCTATTGAGCTGACTCTCCGGAGAGAGTTAGAAGATGTGAACACAGGGGCCGTTATGTCGGCTGGCGGAAAATGGCATTCTCCGGTCTTTTTAACAGCTACCCGTATGTGTAATGACTCAGACAGTCGCAAAATTGTTGGGGGAGACTAAGGGCTCGCGGTGTGGCAGTCTCATTTCGGTTGATGAGTATGGCGACATGAAGGTTGGGCACCCATTGGTCCAATTCGAAAGCGCCTATGCTATTCGTGCCCAGTTACTGTCACACCGTGTTTCCTTAGTTGTGTGTTTGCCT"

new_data = ""

for i in data:
        for k,v in comp_dict.items():
                if i == k:
                        #print k, v, i
                        new_data = new_data + v

new_data = new_data[::-1]

print new_data
